// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1612636377);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1612639756);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1612636017);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1612636257);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1612636497);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.ctrlTab.recentlyUsedOrder", true);
user_pref("browser.download.panel.shown", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.svg", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.xml", true);
user_pref("browser.migration.version", 104);
user_pref("browser.newtab.extensionControlled", true);
user_pref("browser.newtab.privateAllowed", true);
user_pref("browser.newtabpage.activity-stream.impressionId", "{e89e0bde-6381-47f5-98e0-fd435b204cf4}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.policies.applied", true);
user_pref("browser.policies.runOncePerModification.addSearchEngines", "[\"DuckDuckGo Lite\",\"Searx\",\"StartPage\",\"Jive Search\",\"Qwant\",\"MetaGer\",\"Invidious\"]");
user_pref("browser.policies.runOncePerModification.extensionsInstall", "[\"https://addons.cdn.mozilla.net/user-media/addons/607454/ublock_origin-1.32.4-an+fx.xpi\"]");
user_pref("browser.policies.runOncePerModification.extensionsUninstall", "[\"google@search.mozilla.org\",\"bing@search.mozilla.org\",\"amazondotcom@search.mozilla.org\",\"ebay@search.mozilla.org\",\"twitter@search.mozilla.org\"]");
user_pref("browser.policies.runOncePerModification.removeSearchEngines", "[\"Google\",\"Bing\",\"Amazon.com\",\"eBay\",\"Twitter\"]");
user_pref("browser.policies.runOncePerModification.setDefaultSearchEngine", "DuckDuckGo");
user_pref("browser.region.update.first-seen", 1610470546);
user_pref("browser.region.update.region", "BR");
user_pref("browser.search.region", "BR");
user_pref("browser.slowStartup.averageTime", 1515);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.lastColdStartupCheck", 1612639727);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[\"ublock0_raymondhill_net-browser-action\",\"enhancerforyoutube_maximerf_addons_mozilla_org-browser-action\"],\"nav-bar\":[\"home-button\",\"downloads-button\",\"back-button\",\"forward-button\",\"stop-reload-button\",\"urlbar-container\",\"preferences-button\",\"fxa-toolbar-menu-button\",\"addon_darkreader_org-browser-action\",\"_c2c003ee-bd69-42a2-b0e9-6f34222cb046_-browser-action\",\"_react-devtools-browser-action\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\",\"ublock0_raymondhill_net-browser-action\",\"addon_darkreader_org-browser-action\",\"_c2c003ee-bd69-42a2-b0e9-6f34222cb046_-browser-action\",\"_react-devtools-browser-action\",\"enhancerforyoutube_maximerf_addons_mozilla_org-browser-action\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\",\"widget-overflow-fixed-list\"],\"currentVersion\":16,\"newElementCount\":3}");
user_pref("browser.uidensity", 1);
user_pref("devtools.chrome.enabled", true);
user_pref("devtools.command-button-measure.enabled", true);
user_pref("devtools.command-button-noautohide.enabled", true);
user_pref("devtools.command-button-rulers.enabled", true);
user_pref("devtools.command-button-screenshot.enabled", true);
user_pref("devtools.debugger.remote-enabled", true);
user_pref("devtools.dom.enabled", true);
user_pref("devtools.inspector.activeSidebar", "ruleview");
user_pref("devtools.inspector.showAllAnonymousContent", true);
user_pref("devtools.inspector.showUserAgentStyles", true);
user_pref("devtools.performance.enabled", false);
user_pref("devtools.performance.ui.show-platform-data", true);
user_pref("devtools.screenshot.audio.enabled", false);
user_pref("devtools.theme", "dark");
user_pref("devtools.toolbox.tabsOrder", "dom,inspector,webconsole,jsdebugger,netmonitor,styleeditor,performance,memory,storage,accessibility,application");
user_pref("devtools.toolsidebar-height.inspector", 350);
user_pref("devtools.toolsidebar-width.inspector", 700);
user_pref("devtools.toolsidebar-width.inspector.splitsidebar", 350);
user_pref("devtools.webextensions.@react-devtools.enabled", true);
user_pref("distribution.iniFile.exists.appversion", "84.0.2");
user_pref("distribution.iniFile.exists.value", true);
user_pref("distribution.io.gitlab.LibreWolf.bookmarksProcessed", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 33);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20210108230155");
user_pref("extensions.lastAppVersion", "84.0.2");
user_pref("extensions.lastPlatformVersion", "84.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://list/extension");
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.addon@darkreader.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.enhancerforyoutube@maximerf.addons.mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.uBlock0@raymondhill.net", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.{2fc113fc-f01e-427a-8c4a-07b8b2d92f26}", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.{c2c003ee-bd69-42a2-b0e9-6f34222cb046}", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"61de80c0-2621-4268-b477-76aa28b0fb11\",\"screenshots@mozilla.org\":\"205428aa-b914-4030-9a98-367f4912b069\",\"default-theme@mozilla.org\":\"913dbb8c-07c1-4eaa-8cf1-8c22e60a63d7\",\"uBlock0@raymondhill.net\":\"2403cdbd-ca86-46c7-87b2-094cf2a46d84\",\"google@search.mozilla.org\":\"e1b298d7-3d16-4b62-aa01-7c1eec655255\",\"amazondotcom@search.mozilla.org\":\"06400770-b6c3-4ce4-a631-776d626c2202\",\"wikipedia@search.mozilla.org\":\"ad029f32-4e69-4e5e-8b4a-068801246029\",\"bing@search.mozilla.org\":\"302a5d0d-1b74-4dbe-b636-e930635ac2ca\",\"ddg@search.mozilla.org\":\"4d6081b6-1eaf-4974-a8a1-01d08b6d6695\",\"addon@darkreader.org\":\"9c1f1677-2011-471e-a132-9987a65ad96a\",\"{2fc113fc-f01e-427a-8c4a-07b8b2d92f26}\":\"ba3772de-7eb8-4509-bc4d-60de45d79ab2\",\"{c2c003ee-bd69-42a2-b0e9-6f34222cb046}\":\"fa460c02-dd6e-4713-bf3d-00a1fec55f43\",\"@react-devtools\":\"c1bacc66-2651-4504-be9b-cf79faf0749a\",\"enhancerforyoutube@maximerf.addons.mozilla.org\":\"32a2cd56-9635-4743-b900-ed7e67f99dc3\",\"{47bf427e-c83d-457d-9b3d-3db4118574bd}\":\"daaa3eaf-55dc-4e0c-8049-30efb26ec3bd\"}");
user_pref("identity.sendtabpromo.url", "");
user_pref("idle.lastDailyNotification", 1612636682);
user_pref("media.eme.enabled", true);
user_pref("media.gmp-manager.buildID", "20210108230155");
user_pref("media.gmp-manager.lastCheck", 1612636501);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.database.lastMaintenance", 1612636683);
user_pref("places.history.expiration.transient_current_max_pages", 2147483647);
user_pref("pref.downloads.disable_button.edit_actions", false);
user_pref("privacy.purge_trackers.date_in_cookie_database", "0");
user_pref("privacy.sanitize.pending", "[{\"id\":\"shutdown\",\"itemsToClear\":[\"cache\",\"cookies\",\"offlineApps\",\"history\",\"formdata\",\"downloads\",\"sessions\"],\"options\":{}},{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.enterprise_roots enabled", true);
user_pref("security.sandbox.content.tempDirSuffix", "5714ae5d-1ab5-4c42-be6d-d9cc19cd609c");
user_pref("security.sandbox.plugin.tempDirSuffix", "4bb8d37b-f7fe-4165-a455-495b2df1edec");
user_pref("signon.management.page.breach-alerts.enabled", false);
user_pref("signon.management.page.breachAlertUrl", "");
user_pref("signon.management.page.mobileAndroidURL", "");
user_pref("signon.management.page.mobileAppleURL", "");
user_pref("startup.homepage_override_url", "about:blank");
user_pref("startup.homepage_welcome_url", "about:blank");
user_pref("startup.homepage_welcome_url.additional", "");
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1610473548);
user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);
user_pref("toolkit.startup.last_success", 1612644770);
user_pref("toolkit.telemetry.cachedClientID", "ca97afc0-58e7-4163-9299-acb81f699f06");
