[Desktop Entry]
Type=X-GNOME-Metatheme
Name=oomox-arc-one-dark-pro_
Comment=A partially sexual act; when a female (of any species; mostly humanoids) rubs the ears/lobes of a male Ferengi, creating sensual emotions and chemical reactions in the male (and sometimes in the female).
Encoding=UTF-8

[X-GNOME-Metatheme]
Name=oomox-arc-one-dark-pro_
GtkTheme=oomox-arc-one-dark-pro_
IconTheme=oomox-arc-one-dark-pro_
MetacityTheme=oomox-arc-one-dark-pro_
