#! /bin/sh

# Kill all running applications before starting
killall -9 sxhkd compton dunst numlockx unclutter mpDris2

sxhkd &
#bspc monitor -d I II III IV V VI VII VIII IX X
#bspc monitor -d 一 二 三 四 五 六 七 八 九 十 
bspc monitor -d 一 二 三 四 五 六 七 八 九

bspc config border_width         2
bspc config window_gap          12
bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true
#bspc config normal_border_color "#C5123F"
#bspc config focused_border_color "#E91545"

bspc config normal_border_color "#767676"
bspc config focused_border_color "#bfc7d5"


# https://github.com/Javyre/bspwm
bspc config border_radius 6

# Window rules
#   Open in specific workspace
bspc rule -a Termite desktop='^1' follow=on
bspc rule -a qutebrowser desktop='^2' follow=on
bspc rule -a Chromium desktop='^2' follow=on
bspc rule -a Firefox desktop='^2'  follow=on
bspc rule -a Mousepad desktop='^3' follow=on
bspc rule -a Subl3 desktop='^3' follow=on
bspc rule -a Code desktop='^3' follow=on
bspc rule -a Notepadqq desktop='^3' follow=on
bspc rule -a Deluge desktop='^4' follow=on
bspc rule -a qBittorrent desktop='^9' follow=on
bspc rule -a Nemo desktop='^5' follow=on
bspc rule -a Thunar desktop='^5' follow=on
bspc rule -a Spacefm desktop='^5' follow=on
bspc rule -a TelegramDesktop desktop='^6' follow=on
bspc rule -a Zathura desktop='^8' follow=on state=tiled
bspc rule -a Steam desktop='^9' follow=on
bspc rule -a mpv desktop=^4 follow=on state=tiled
bspc rule -a Sxiv desktop=^4 follow=on state=tiled
bspc rule -a Viewnior desktop=^4 follow=on state=tiled

#   Open specific windows in floating mode
bspc rule -a Xfce4-appfinder state=floating focus=on floating=on 
bspc rule -a alsamixer state=floating focus=on
bspc rule -a GParted state=floating focus=on
bspc rule -a Lxappearance state=floating focus=on
bspc rule -a nitrogen state=floating focus=on
bspc rule -a SimpleScreenRecorder state=floating focus=on
bspc rule -a Pulseffects state=floating focus=on
bspc rule -a Pulseaudio-equalizer-gtk state=floating focus=on
bspc rule -a Pavucontrol state=floating focus=on center=on
bspc rule -a Viewnior focus=on state=tiled

feh --bg-fill "/home/zsucrilhos/Desktop/1572611.jpg"

dunst &
compton -b --config ~/.config/compton/compton.conf &
unclutter &
numlockx on &
xsetroot -cursor_name left_ptr &
/usr/bin/mpDris2 &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
xautolock -time 5 -locker 'dm-tool switch-to-greeter'

/home/zsucrilhos/_my-scripts/polybarstart-bspwm
/home/zsucrilhos/_my-scripts/dpms.sh
/home/zsucrilhos/_my-scripts/lightsOn.sh

